[package]
name = "aquilion"
version = "0.1.0"
edition = "2021"
authors = ["The Maintainers of Aquilion"]
homepage = "https://github.com/lemosep"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = "0.9.8"
volatile = "0.6.1"
